name: My first github action

on: push

jobs:
  HelloWorld:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: npm install

    - name: Say hello
      run: echo Hello World
